workflows:
  ios-xtool-deploy:
    name: iOS xtool deployment
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic

    environment:
      groups:
        - Wem
      vars:
        APP_NAME: "WebXR Shell"
        BUNDLE_ID: "com.wem.xrshell"
        START_URL: "https://threejs.org/examples/webxr_ar_hittest.html"
        XCODE_SCHEME: "xrshell"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Inject Configuration
        script: |
          echo "Injecting configuration..."
          
          PLIST_PATH="Info.plist"
          CONFIG_PATH="Sources/xrshell/AppConfig.swift"

          plutil -replace CFBundleIdentifier -string "$BUNDLE_ID" "$PLIST_PATH"
          plutil -replace CFBundleDisplayName -string "$APP_NAME" "$PLIST_PATH"
          plutil -replace CFBundleName -string "$APP_NAME" "$PLIST_PATH"
          
          cat <<EOF > "$CONFIG_PATH"
          import Foundation

          struct AppConfig {
              static let startURL = "$START_URL"
          }
          EOF
          
          echo "Configuration injected: $APP_NAME ($BUNDLE_ID) -> $START_URL"

      - name: Generate Xcode Project
        script: |
          swift package generate-xcodeproj --skip-extra-files
          
          ruby -e '
            require "xcodeproj"
            project_path = "xrshell.xcodeproj"
            plist_path = "Info.plist"
            project = Xcodeproj::Project.open(project_path)
            project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings["INFOPLIST_FILE"] = plist_path
                config.build_settings["PRODUCT_BUNDLE_IDENTIFIER"] = ENV["BUNDLE_ID"]
                config.build_settings["MARKETING_VERSION"] = "1.0.0"
                config.build_settings["CURRENT_PROJECT_VERSION"] = "1"
                config.build_settings["SWIFT_VERSION"] = "5.0"
              end
            end
            project.save
          '

      # --- AUTOMATIC CODE SIGNING START ---
      - name: Initialize Keychain
        script: keychain initialize

      - name: Fetch Signing Files
        script: |
          # This command uses the API Key and CERTIFICATE_PRIVATE_KEY to 
          # generate a certificate and profile if they don't exist.
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add Certificates to Keychain
        script: keychain add-certificates

      - name: Apply Provisioning Profiles
        script: xcode-project use-profiles --project "xrshell.xcodeproj"
      # --- AUTOMATIC CODE SIGNING END ---

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "xrshell.xcodeproj" \
            --scheme "$XCODE_SCHEME" \
            --configuration Release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false