workflows:
  ios-xtool-deploy:
    name: iOS xtool deployment
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic

    environment:
      groups:
        - Wem
      vars:
        APP_NAME: "WebXR Shell"
        BUNDLE_ID: "com.wem.xrshell"
        START_URL: "https://threejs.org/examples/webxr_ar_hittest.html"
        XCODE_SCHEME: "xrshell"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Inject Configuration
        script: |
          echo "Injecting AppConfig..."
          # Only AppConfig needs injection. 
          # Info.plist and project.yml are handled by the repo and XcodeGen.
          CONFIG_PATH="Sources/xrshell/AppConfig.swift"
          
          cat <<EOF > "$CONFIG_PATH"
          import Foundation
          struct AppConfig {
              static let startURL = "$START_URL"
          }
          EOF

      - name: Generate App Icons
        script: |
          echo "Generating App Icons..."
          ICON_SOURCE="icon.png"
          if [ ! -f "$ICON_SOURCE" ]; then
            echo "⚠️ No icon.png found! Downloading placeholder..."
            curl -o "$ICON_SOURCE" https://dummyimage.com/1024x1024/007AFF/ffffff.jpg&text=XR
          fi

          ASSETS_DIR="Sources/xrshell/Assets.xcassets"
          ICONSET_DIR="$ASSETS_DIR/AppIcon.appiconset"
          mkdir -p "$ICONSET_DIR"

          cat <<EOF > "$ICONSET_DIR/Contents.json"
          {
            "images": [
              {"size":"20x20","idiom":"iphone","filename":"Icon-20@2x.png","scale":"2x"},
              {"size":"20x20","idiom":"iphone","filename":"Icon-20@3x.png","scale":"3x"},
              {"size":"29x29","idiom":"iphone","filename":"Icon-29@2x.png","scale":"2x"},
              {"size":"29x29","idiom":"iphone","filename":"Icon-29@3x.png","scale":"3x"},
              {"size":"40x40","idiom":"iphone","filename":"Icon-40@2x.png","scale":"2x"},
              {"size":"40x40","idiom":"iphone","filename":"Icon-40@3x.png","scale":"3x"},
              {"size":"60x60","idiom":"iphone","filename":"Icon-60@2x.png","scale":"2x"},
              {"size":"60x60","idiom":"iphone","filename":"Icon-60@3x.png","scale":"3x"},
              {"size":"20x20","idiom":"ipad","filename":"Icon-20.png","scale":"1x"},
              {"size":"20x20","idiom":"ipad","filename":"Icon-20@2x.png","scale":"2x"},
              {"size":"29x29","idiom":"ipad","filename":"Icon-29.png","scale":"1x"},
              {"size":"29x29","idiom":"ipad","filename":"Icon-29@2x.png","scale":"2x"},
              {"size":"40x40","idiom":"ipad","filename":"Icon-40.png","scale":"1x"},
              {"size":"40x40","idiom":"ipad","filename":"Icon-40@2x.png","scale":"2x"},
              {"size":"76x76","idiom":"ipad","filename":"Icon-76.png","scale":"1x"},
              {"size":"76x76","idiom":"ipad","filename":"Icon-76@2x.png","scale":"2x"},
              {"size":"83.5x83.5","idiom":"ipad","filename":"Icon-83.5@2x.png","scale":"2x"},
              {"size":"1024x1024","idiom":"ios-marketing","filename":"Icon-1024.png","scale":"1x"}
            ],
            "info": { "version": 1, "author": "xcode" }
          }
          EOF

          function resize() {
            sips -z $1 $1 -s format png "$ICON_SOURCE" --out "$ICONSET_DIR/$2" > /dev/null
          }

          resize 40 "Icon-20@2x.png"
          resize 60 "Icon-20@3x.png"
          resize 58 "Icon-29@2x.png"
          resize 87 "Icon-29@3x.png"
          resize 80 "Icon-40@2x.png"
          resize 120 "Icon-40@3x.png"
          resize 120 "Icon-60@2x.png"
          resize 180 "Icon-60@3x.png"
          resize 20 "Icon-20.png"
          resize 29 "Icon-29.png"
          resize 40 "Icon-40.png"
          resize 76 "Icon-76.png"
          resize 152 "Icon-76@2x.png"
          resize 167 "Icon-83.5@2x.png"
          resize 1024 "Icon-1024.png"
          echo "✅ Icons generated."

      - name: Generate Xcode Project (XcodeGen)
        script: |
          brew install xcodegen
          xcodegen generate

      # --- AUTOMATIC CODE SIGNING START ---
      - name: Initialize Keychain
        script: keychain initialize

      - name: Fetch Signing Files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add Certificates to Keychain
        script: keychain add-certificates

      - name: Apply Provisioning Profiles
        script: xcode-project use-profiles --project "xrshell.xcodeproj"
      # --- AUTOMATIC CODE SIGNING END ---

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "xrshell.xcodeproj" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false