name: Cyango
options:
  bundleIdPrefix: ${BUNDLE_ID}
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
packages:
  WebXRKit:
    path: ./WebXRKit
targets:
  HelloXR:
    type: application
    platform: iOS
    sources:
      - path: Sources/HelloXR
    dependencies:
      - target: HelloXRClip
        embed: true
      - package: WebXRKit
        product: WebXRKit
    settings:
      # Points to the Main App Plist
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      MARKETING_VERSION: 1.2.0
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_VERSION: 5.0
      CODE_SIGN_ENTITLEMENTS: "HelloXR.entitlements"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: 1

  HelloXRClip:
    type: application.on-demand-install-capable
    platform: iOS
    sources:
      - path: Sources/HelloXR
    dependencies:
      - package: WebXRKit
        product: WebXRKit
    settings:
      # Points to the App Clip Plist
      INFOPLIST_FILE: Info-Clip.plist
      GENERATE_INFOPLIST_FILE: NO
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}.Clip
      MARKETING_VERSION: 1.2.0
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_VERSION: 5.0
      CODE_SIGN_ENTITLEMENTS: "HelloXRClip.entitlements"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: 1