name: xrshell
options:
  bundleIdPrefix: ${BUNDLE_ID}
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  xrshell:
    type: application
    platform: iOS
    sources:
      - path: Sources/xrshell
    settings:
      # This links to your existing Info.plist in the root
      INFOPLIST_FILE: Info.plist
      
      # Uses the environment variable from Codemagic
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      
      # Build Settings
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0.0
      SWIFT_VERSION: 5.0
      
      # Asset Settings
      RECOMMENDED_ASSET_TYPES: "appicon"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"