name: xrshell
options:
  bundleIdPrefix: ${BUNDLE_ID}
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  xrshell:
    type: application
    platform: iOS
    sources:
      - path: Sources/xrshell
    settings:
      # 1. Point to your static file
      INFOPLIST_FILE: Info.plist
      
      # 2. CRITICAL CHANGE: Turn this OFF to prevent Xcode from stripping keys
      GENERATE_INFOPLIST_FILE: NO
      
      # 3. This setting is still good to have, but the plist key is now the authority
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      RECOMMENDED_ASSET_TYPES: "appicon"

      # Standard Settings
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0.0
      SWIFT_VERSION: 5.0