name: ${APP_NAME}
options:
  bundleIdPrefix: ${BUNDLE_ID}
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top
  preGenCommand: sh Scripts/generate_icons.sh

packages:
  WebXRKit:
    path: ./WebXRKit

targets:
  # --- Main Application ---
  WebXRApp:
    type: application
    platform: iOS
    productName: ${APP_NAME}
    sources:
      - path: Sources/WebXRApp
    dependencies:
      - target: WebXRClip
        embed: true
      - package: WebXRKit
        product: WebXRKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      MARKETING_VERSION: ${VERSION}
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_VERSION: 5.0
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: 1
      INFOPLIST_KEY_CFBundleDisplayName: ${APP_NAME}
    
    info:
      path: Generated/Info.plist
      properties:
        WB_START_URL: ${START_URL} 
        CFBundleShortVersionString: ${VERSION}
        CFBundleVersion: ${BUILD_NUMBER}
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities: [arm64, arkit]
        NSCameraUsageDescription: "Camera access is required for AR experiences."
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]

    entitlements:
      path: Generated/WebXRApp.entitlements
      properties:
        com.apple.developer.associated-domains: ["appclips:${DOMAIN_URL}"]

  # --- App Clip ---
  WebXRClip:
    type: application.on-demand-install-capable
    platform: iOS
    productName: ${APP_NAME}Clip
    sources:
      - path: Sources/WebXRApp
    dependencies:
      - package: WebXRKit
        product: WebXRKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}.Clip
      MARKETING_VERSION: ${VERSION}
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_VERSION: 5.0
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: 1
      INFOPLIST_KEY_CFBundleDisplayName: ${APP_NAME}

    info:
      path: Generated/Info-Clip.plist
      properties:
        WB_START_URL: ${START_URL} 
        CFBundleShortVersionString: ${VERSION}
        CFBundleVersion: ${BUILD_NUMBER}
        LSRequiresIPhoneOS: true
        NSAppClip:
          NSAppClipRequestEphemeralUserNotification: false
          NSAppClipRequestLocationConfirmation: false
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities: [arm64, arkit]
        NSCameraUsageDescription: "Camera access is required for AR experiences."
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]

    entitlements:
      path: Generated/WebXRClip.entitlements
      properties:
        com.apple.developer.on-demand-install-capable: true
        com.apple.developer.associated-domains: ["appclips:${DOMAIN_URL}"]
        com.apple.developer.parent-application-identifiers:
          - "$(AppIdentifierPrefix)${BUNDLE_ID}"