name: ${projectName}
options:
  bundleIdPrefix: ${bundleIdPrefix}
  deploymentTarget:
    iOS: "${deploymentTarget}"
  xcodeVersion: "${xcodeVersion}"
packages:
  WebXRKit:
    path: ./WebXRKit
targets:
  MainApp:
    type: application
    platform: iOS
    sources:
      - path: Sources/App
    dependencies:
      - target: MainAppClip
        embed: true
      - package: WebXRKit
        product: WebXRKit
    settings:
      # Points to the Main App Plist
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO
      PRODUCT_BUNDLE_IDENTIFIER: ${mainBundleId}
      MARKETING_VERSION: ${version}
      CURRENT_PROJECT_VERSION: ${buildNumber}
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_VERSION: 5.0
      CODE_SIGN_ENTITLEMENTS: "MainApp.entitlements"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: 1

  MainAppClip:
    type: application.on-demand-install-capable
    platform: iOS
    sources:
      - path: Sources/App
    dependencies:
      - package: WebXRKit
        product: WebXRKit
    settings:
      # Points to the App Clip Plist
      INFOPLIST_FILE: Info-Clip.plist
      GENERATE_INFOPLIST_FILE: NO
      PRODUCT_BUNDLE_IDENTIFIER: ${clipBundleId}
      MARKETING_VERSION: ${version}
      CURRENT_PROJECT_VERSION: ${buildNumber}
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_VERSION: 5.0
      CODE_SIGN_ENTITLEMENTS: "MainAppClip.entitlements"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: 1